"""Add ext in ProjectImage

Revision ID: 4eacdc645a6b
Revises: 62b30270d0eb
Create Date: 2024-09-22 00:18:22.152234

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4eacdc645a6b'
down_revision = '62b30270d0eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_images', sa.Column('ext', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project_images', 'ext')
    # ### end Alembic commands ###
